const fs = require('fs');


var titles = [
    { name: "15年01月01日 拥抱每一天- 新年特辑：拥抱耶稣的心--像祂一样的心怀", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月02日 拥抱每一天- 新年特辑：拥抱耶稣的心--饶恕的心", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月03日 拥抱每一天- 新年特辑：拥抱耶稣的心--怜恤的心", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月04日 拥抱每一天- 新年特辑：拥抱耶稣的心--倾听的心", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月05日 拥抱每一天- 新年特辑：拥抱耶稣的心--专注的心", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月06日 拥抱每一天- 新年特辑：拥抱耶稣的心--敬拜的心", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月07日 拥抱每一天- 新年特辑：拥抱耶稣的心--喜乐的心", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月08日 拥抱每一天- 新年特辑：拥抱耶稣的心--诚实的心", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月09日 拥抱每一天- 新年特辑：拥抱耶稣的心--盼望的心", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月10日 拥抱每一天- 新年特辑：拥抱耶稣的心--忍耐的心", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月11日 拥抱每一天- 智慧语录；拥抱小语；神的叮咛我最爱：信我的人，必然复活。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月12日 拥抱每一天- 智慧语录；拥抱小语；寻找生命的真光：我生命中两个离奇的五年", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月13日 拥抱每一天- 智慧语录；拥抱小语；千里思念万里情：圣经中三面镜子", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月14日 拥抱每一天- 智慧语录；拥抱小语；诗情细语话人生：自拍女孩心", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月15日 拥抱每一天- 智慧语录；说个故事给你听：写在新的岁数上", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月16日 拥抱每一天- 智慧语录；拥抱小语；亮丽人生不是梦：欧拉--应用数学家", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月17日 拥抱每一天- 今晚，我们听书：洞穴人是我们的祖先吗？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月18日 拥抱每一天- 智慧语录；拥抱小语；神的叮咛我最爱：人的逼迫成就了神的旨意", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月19日 拥抱每一天- 智慧语录；拥抱小语；寻找生命的真光：无法掌控的人生", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月20日 拥抱每一天- 智慧语录；拥抱小语；千里思念万里情：2014年时代杂志的封面人物", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月21日 拥抱每一天- 智慧语录；拥抱小语；诗情细语话人生：只要有梦想", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月22日 拥抱每一天- 智慧语录；说个故事给你听：一个母亲拥抱杀儿凶手的故事", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月23日 拥抱每一天- 智慧语录；拥抱小语；亮丽人生不是梦：安慰医治心力交瘁的人", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月24日 拥抱每一天- 今晚，我们听书：从猿进化到人究竟要多久；丈夫天生需要帮助", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月25日 拥抱每一天- 智慧语录；神的叮咛我最爱：在神的时间表里成就神的事工", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月26日 拥抱每一天- 智慧语录；拥抱小语；寻找生命的真光：选择放手--留美女博士的挣扎", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月27日 拥抱每一天- 智慧语录；拥抱小语；千里思念万里情：敬天爱人、求同存异的再思", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月28日 拥抱每一天- 智慧语录；拥抱小语；诗情细语话人生：璐璐的心事", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月29日 拥抱每一天- 智慧语录；拥抱小语：说个故事给你听：心执风筝", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月30日 拥抱每一天- 智慧语录；亮丽人生不是梦：数学大师柯西的故事", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年01月31日 拥抱每一天- 今晚，我们听书：人类不需要进化；妻子--荣耀的帮助者", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAxMzEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月01日 拥抱每一天- 智慧语录；神的叮咛我最爱：为主而做，必不徒然", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月02日 拥抱每一天- 智慧语录；拥抱小语；寻找生命的真光：吸毒的青春期", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月03日 拥抱每一天- 智慧语录；拥抱小语；千里思念万里情：在公司五句千万不能说的话", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月04日 拥抱每一天- 智慧语录；拥抱小语；诗情细语话人生：曼德拉传奇的一生", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月05日 拥抱每一天- 智慧语录；拥抱小语：觅非波舍之家", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月06日 拥抱每一天- 智慧语录；亮丽人生不是梦：安慰医治心力交瘁的人", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月07日 拥抱每一天- 今晚，我们听书：探索恐龙；预备成为帮助者", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月08日 拥抱每一天- 智慧语录；神的叮咛我最爱：除祂以外，别无拯救", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月09日 拥抱每一天- 智慧语录；拥抱小语；寻找生命的真光：投资天国的股票", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月10日 拥抱每一天- 情人节特辑：莫让此情成追忆（一）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月11日 拥抱每一天- 情人节特辑：莫让此情成追忆（二）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月12日 拥抱每一天- 情人节特辑：莫让此情成追忆（三）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月13日 拥抱每一天- 情人节特辑：莫让此情成追忆（四）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月14日 拥抱每一天- 情人节特辑：莫让此情成追忆（五）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月15日 拥抱每一天- 智慧语录；神的叮咛我最爱：耶稣基督是我们的生命之王", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月16日 拥抱每一天- 智慧语录；寻找生命的真光：父与子，直面血癌、脑癌与精神病", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月17日 拥抱每一天- 智慧语录；拥抱小语；千里思念万里情：职场危情--比能力更重要的12种品格", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月18日 拥抱每一天- 春节特辑（一）：扩大你的视野（1）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月19日 拥抱每一天- 春节特辑（二）：扩大你的视野（2）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月20日 拥抱每一天- 春节特辑（三）：提高你的期待层次", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月21日 拥抱每一天- 春节特辑（四）：培养健康的自我形象", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月22日 拥抱每一天- 春节特辑（五）：说出改变生命的话语", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月23日 拥抱每一天- 春节特辑（六）：让过去成为过去", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月24日 拥抱每一天- 春节特辑（七）：在困境中找到力量", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月25日 拥抱每一天- 春节特辑（八）：等候神的时间表", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月26日 拥抱每一天- 春节特辑（九）：困境中的力量", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月27日 拥抱每一天- 春节特辑（十）：为施予而活", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年02月28日 拥抱每一天- 春节特辑（十一）：选择快乐的度过今天", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAyMjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月01日 拥抱每一天- 智慧语录；神的叮咛我最爱：十字架是神的荣耀", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月02日 拥抱每一天- 智慧语录；拥抱小语；寻找生命的真光：复苏的渐冻人", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月03日 拥抱每一天- 智慧语录；千里思念万里情：给男人的12诫", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月04日 拥抱每一天- 智慧语录；拥抱小语；诗情细语话人生：无价的六元钱", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月05日 拥抱每一天- 智慧语录；拥抱小语；说个故事给你听：隐形的翅膀", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月06日 拥抱每一天- 智慧语录；拥抱小语；亮丽人生不是梦：在沙漠里弹琴的人", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月07日 拥抱每一天- 今晚听书：恐龙是否与圣经的记载相一致呢？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月08日 拥抱每一天- 智慧语录；神的叮咛我最爱：悔改的祷告", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月09日 拥抱每一天- 智慧语录；拥抱小语；寻找生命的真光：别让孩子迷失在同伴的压力里", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月10日 拥抱每一天- 智慧语录；千里思念万里情：婆媳关系好坏取决于老公", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月11日 拥抱每一天- 智慧语录；拥抱小语；诗情细语话人生：美国小镇的慈善箱", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月12日 拥抱每一天- 智慧语录；拥抱小语；说个故事给你听：上帝的画笔", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月13日 拥抱每一天- 智慧语录；亮丽人生不是梦：我经历了神的爱", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月14日 拥抱每一天- 今晚听书：帕鲁克西河床上的脚印", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月15日 拥抱每一天- 智慧语录；神的叮咛我最爱：主的道要审判世人", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月16日 拥抱每一天- 智慧语录；拥抱小语；寻找生命的真光：喜剧之王死于抑郁的悲剧", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月17日 拥抱每一天- 智慧语录；拥抱小语；千里思念万里情：做个有教养的人", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月18日 拥抱每一天- 智慧语录；诗情细语话人生：一个人成功的标志是什么？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月19日 拥抱每一天- 智慧语录；拥抱小语；说个故事给你听：美好的等待", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月20日 拥抱每一天- 智慧语录；亮丽人生不是梦：一个医生的信仰", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月21日 拥抱每一天- 今晚听书：进化论者面对更多的难题", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月22日 拥抱每一天- 智慧语录；神的叮咛我最爱：不要走入黑暗里。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月23日 拥抱每一天- 智慧语录；拥抱小语；寻找生命的真光：后会无期，生有可恋。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月24日 拥抱每一天- 智慧语录；千里思念万里情：说话的艺术。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月25日 拥抱每一天- 复活节特辑：《使徒信经》对当代人的意义（一）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月26日 拥抱每一天- 复活节特辑：《使徒信经》对当代人的意义（二）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月27日 拥抱每一天- 复活节特辑：《使徒信经》对当代人的意义（三）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月28日 拥抱每一天- 复活节特辑：《使徒信经》对当代人的意义（四）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月29日 拥抱每一天- 复活节特辑：《使徒信经》对当代人的意义（五）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月30日 拥抱每一天- 复活节特辑：《使徒信经》对当代人的意义（六）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年03月31日 拥抱每一天- 复活节特辑：《使徒信经》对当代人的意义（七）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTAzMzEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" }
];

var songs = JSON.parse(fs.readFileSync('ee2015_spring_songs.json', 'utf8'));
songs.forEach(function(song, indexId) {


    song.title = titles[indexId].name;


});

fs.writeFile("./ee2015_spring_songs_with_title.json", JSON.stringify(songs, null, '\t'));