const fs = require('fs');

var season = "spring";

var titles = [
    { name: "16年01月01日 拥抱每一天- 新年特别节目：以信心面向2016年；追求丰盛的人生；新年礼物。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月02日 拥抱每一天- 智慧语录：写给未来的你；用智慧演绎人生：家里来了个日本小孩。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月03日 拥抱每一天- 智慧语录：一生不白搭？神的叮咛我最爱：母亲的爱。（沈保罗牧师）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月04日 拥抱每一天- 智慧语录：人生是一种领悟；拥抱小语：所谓素质不过是细节（程枫）；寻找生命的真光：妈妈，你温柔吗？（武颖）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月05日 拥抱每一天- 智慧语录：感情再好，也需要距离；拥抱小语：你以为你是谁？（程枫）；千里思念万里情：向着标杆直跑。（杨东川牧师）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月06日 拥抱每一天- 智慧语录：愿你成为最好的女子；诗情细语话人生：德国法西斯军人的底线。（天路客）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月07日 拥抱每一天- 智慧语录：你正在交往的人，是真的爱你吗？；说个故事给你听：方莉的日记。（冠男）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月08日 拥抱每一天- 智慧语录：中年之后；亮丽人生不是梦：成长的季节。（陆平）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月09日 拥抱每一天- 智慧语录：友不在多，贵在风雨同行；拥抱小语：激发孩子的内在动力（雅薇）；用智慧演绎人生：人生的最后一刻，你后悔吗？（冠男）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月10日 拥抱每一天- 智慧语录：我很幸福；神的叮咛我最爱：主的受难应验旧约先知的预言。（沈保罗牧师）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月11日 拥抱每一天- 智慧语录：我不需要手和脚，因为上帝背着我；拥抱小语：在不起眼的工作中作光作盐（程枫）；寻找生命的真光：别把妈妈埋进坑里。（武颖）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月12日 拥抱每一天- 智慧语录：让人顿悟的几句话；拥抱小语：伊丽莎白艾略特经过荣耀之门进入永恒（程枫）；千里思念万里情：探讨自杀之防范。（杨东川牧师）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月13日 拥抱每一天- 智慧语录：女人四十；拥抱小语：丈夫的责任（雅薇）；诗情细语话人生：认真，是一种可怕的力量。（天路客张本）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月14日 拥抱每一天- 智慧语录：不和别人比，好好活自己；拥抱小语：如何看待生命中的试炼（雅薇）；说个故事给你听：走出抑郁。（琦睿）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月15日 拥抱每一天- 智慧语录：如果男人这样待你，嫁给他又何妨；亮丽人生不是梦：好时间，坏时间。（陆平）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月16日 拥抱每一天- 智慧语录：单纯与复杂；拥抱小语：未来在上帝手中（雅薇）；用智慧演绎人生：从圣经中看父亲的责任。（冠男）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月17日 拥抱每一天- 智慧语录：要记得，也要学习；神的叮咛我最爱：成了。（沈保罗牧师）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月18日 拥抱每一天- 智慧语录：生命的境界；拥抱小语：宠辱不惊（程枫）；寻找生命的真光：80年跟着证据走，终于找到神。（武颖）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月19日 拥抱每一天- 智慧语录：好老公的标准；拥抱小语：好男人是一座教堂（程枫）；千里思念万里情：再谈同性恋。（杨东川牧师）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月20日 拥抱每一天- 智慧语录：一生学习做人；诗情细语话人生：鲁迅批判中国，奥古斯丁践踏自己。（张本）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月21日 拥抱每一天- 智慧语录：让开心成为一种习惯；拥抱小语：恩典与偶像（雅薇）；说个故事给你听：缺少的不是幸福，而是能感受幸福的心。（琦睿）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月22日 拥抱每一天- 智慧语录：我们都是人生的过客；拥抱小语：请以谦卑、爱和尊重对待你周遭的人（程枫）；亮丽人生不是梦：第二次机会。（陆平）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月23日 拥抱每一天- 智慧语录：说话的艺术；拥抱小语：路易斯的生死之恋（雅薇）；用智慧演绎人生：怎样陪宝宝成长，同时拥有最好的自己。（冠男）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月24日 拥抱每一天- 智慧语录：诺不轻许，许则为之；神的叮咛我最爱：十架大爱，转化人生。（沈保罗牧师）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月25日 拥抱每一天- 智慧语录：你读完，一定会放下很多事；拥抱小语：你是为自己的将来打工（程枫）；寻找生命的真光：昨夜摇滚，今日磐石，17年吸毒史。（武颖）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月26日 拥抱每一天- 智慧语录：天父儿女一家亲；拥抱小语：祥潘的生命故事（程枫）；千里思念万里情：如何过正常的基督徒生活。（杨东川牧师）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月27日 拥抱每一天- 智慧语录：多少人都输在这个字上；拥抱小语：用一生诠释了最好的爱情（伟丽）；诗情细语话人生：幽默化解尴尬、改变人生的24个字。（天路客：张本）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月28日 拥抱每一天- 智慧语录：没事，你还有我；说个故事给你听：只要有人在我身上看见神的爱，那一刻都值得了。（程枫）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月29日 拥抱每一天- 智慧语录：处理好自己与身边人的关系；亮丽人生不是梦：相连，人类基本的需要。（陆平）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月30日 拥抱每一天- 智慧语录：当一个人男人回复你的微信很慢时；拥抱小语：失败是一所神学院；用智慧演绎人生：特长的培养。（冠男）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年01月31日 拥抱每一天- 智慧语录：心里明白就好；神的叮咛我最爱：他复活了。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAxMzEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月01日 拥抱每一天- 智慧语录：给自己开一扇乐观的窗；拥抱小语：这一生最美的故事；寻找生命的真光：世界上最醜女人的美丽人生。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月02日 拥抱每一天- 智慧语录：向着标杆直跑，让人生无憾无悔；拥抱小语：人生最重要的是一颗善心；千里思念万里情：重温祷告学。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月03日 拥抱每一天- 智慧语录：当今世界最大的需要是什么；拥抱小语：伟大的信念与宣言；诗情细语话人生：大师的杰作。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月04日 拥抱每一天- 说个故事给你听：在极重的患难中经历神奇妙的爱。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月05日 拥抱每一天- 智慧语录：透视人生的经验之谈；拥抱小语：57分钱成就了一座大教堂；亮丽人生不是梦：最大乱度。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月06日 拥抱每一天- 智慧语录：带上最美的笑容，且行且珍惜；拥抱小语：基督徒为什么比一般人更喜乐；用智慧演绎人生：爱因斯坦给他女儿的一封信。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月07日 拥抱每一天- 春节特辑：热爱生命，拥抱今天（一）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月08日 拥抱每一天- 春节特辑：热爱生命，拥抱今天（二）：明白你的影响力。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月09日 拥抱每一天- 春节特辑：热爱生命，拥抱今天（三）：抓住最重要的。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月10日 拥抱每一天- 春节特辑：热爱生命，拥抱今天（四）：善用你所拥有的机会之门。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月11日 拥抱每一天- 春节特辑：热爱生命，拥抱今天（五）：不要让攻击伤害击倒你。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月12日 拥抱每一天- 春节特辑：热爱生命，拥抱今天（六）：享受美好关系。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月13日 拥抱每一天- 春节特辑：热爱生命，拥抱今天（七）：发现他人的需要。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月14日 拥抱每一天- 春节特辑：热爱生命，拥抱今天（八）：造就身边的人。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月15日 拥抱每一天- 春节特辑：热爱生命，拥抱今天（九）：接受神无条件的爱。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月16日 拥抱每一天- 春节特辑：热爱生命，拥抱今天（十）：保持正确的观点。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月17日 拥抱每一天- 智慧语录：丘吉尔的经典名言；拥抱小语：大风琴（程枫）；诗情细语话人生：女足队员韩瑞的信仰见证。（天路客：红花）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月18日 拥抱每一天- 智慧语录：别人的评价，真的不重要；说个故事给你听：上帝背着我。（海云）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月19日 拥抱每一天- 智慧语录：伤不起的感情，疼不起的心灵；拥抱小语：留几枚柿子在树上吧！（雅薇）；亮丽人生不是梦：相连的重要性。（陆平）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月20日 拥抱每一天- 智慧语录：人这一辈子，你要怎么过；拥抱小语：乐意分享（程枫）；用智慧演绎人生：中国最需要教育的不是孩子，而是大人。（冠男）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月21日 拥抱每一天- 智慧语录：做人做事看胸襟；神的叮咛我最爱：最大的冲击。（沈保罗牧师）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月22日 拥抱每一天- 智慧语录：简简单单过一生；拥抱小语：蝴蝶的教训（程枫）；寻找生命的真光：我并不是你认为的那个我。（武颖）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月23日 拥抱每一天- 智慧语录：感谢那些看透了我，却一直陪伴在我身边的人；拥抱小语：人老了，是什么样的感觉？（雅薇）；千里思念万里情：圣经对世人的劝勉。（杨东川牧师）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月24日 拥抱每一天- 智慧语录：学习享受生活，别让生活操纵你；拥抱小语：你也在井里吗？（程枫）；诗情细语话人生：为我唱首歌吧！（朝朝）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月25日 拥抱每一天- 智慧语录：感情请留给那些在乎你的人；拥抱小语：陶塑孩子心灵的三个基本原则（雅薇）；说个故事给你听：上帝怎样改变了一个泼妇。（琦睿）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月26日 拥抱每一天- 智慧语录：做大事之人的特征；亮丽人生不是梦：依附的好处。（陆平）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月27日 拥抱每一天- 智慧语录：人到中年，总在撕裂中前行；用智慧演绎人生：与孩子的相处之道。（冠男）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月28日 拥抱每一天- 智慧语录：意味深长的君臣对话；神的叮咛我最爱：我也照样差遣你们。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年02月29日 拥抱每一天- 智慧语录：别对你爱的人飙狠话；拥抱小语：盯住别人的缺点最终伤害的是自己；寻找生命的真光：世界上最有权力的女人的信仰。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAyMjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月01日 拥抱每一天- 智慧语录：相遇、想惜、相守；拥抱小语：得体比好看重要得多了；千里思念万里情：感恩与忘恩。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月02日 拥抱每一天- 智慧语录：争的是理，输的是情；诗情细语话人生：丢了翅膀，他仍是天使。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月03日 拥抱每一天- 智慧语录：我愿这颗心，宁静如大海；说个故事给你听：暗室之后蔡苏娟", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月04日 拥抱每一天- 智慧语录：一生的果效是由心发出；拥抱小语：富而不贵是种痛；亮丽人生不是梦：无法与人相连的症状。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月05日 拥抱每一天- 智慧语录：人生的三样东西；拥抱小语：你无趣，是因为少了一些仪式感；用智慧演绎人生：为何爸爸带大的宝宝智商更高。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月06日 拥抱每一天- 女人如何更幸福（一）方恩、施瑋", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月07日 拥抱每一天- 女人如何更幸福（二）方恩、施瑋", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月08日 拥抱每一天- 女人如何更幸福（三）方恩、施瑋", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月09日 拥抱每一天- 女人如何更幸福（四）方恩、施瑋", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月10日 拥抱每一天- 女人如何更幸福（五）方恩、施瑋", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月11日 拥抱每一天- 女人如何更幸福（六）方恩、施瑋", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月12日 拥抱每一天- 女人如何更幸福（七）方恩、施瑋", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月13日 拥抱每一天- 智慧语录：我也有心酸和委屈，能说个谁听；神的叮咛我最爱：信了他，就可以因他的名的生命。（沈保罗牧师）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月14日 拥抱每一天- 智慧语录：懂了这些，幸福相伴相随；拥抱小语：两则小故事的启示（程枫）；寻找生命的真光：从KTV公主到上帝的公主。（武颖）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月15日 拥抱每一天- 智慧语录：拥有幸福，如此简单；拥抱小语：花时间，与神独处（琦睿）；千里思念万里情：属灵恩赐的重要性。（杨东川牧师）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月16日 拥抱每一天- 诗情细语话人生：从简爱再思人生之最。（天路客：黄蕾）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月17日 拥抱每一天- 说个故事给你听：从老虎到仆人。（海云）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月18日 拥抱每一天- 智慧语录：谁把你放在心上，一看便知；拥抱小语：心灵的品级（雅薇）：亮丽人生不是梦：缺乏相连的生命之缺失。（陆平）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月19日 拥抱每一天- 智慧语录：有一天我去世了；拥抱小语：所做之善，回到身边（雅薇）；用智慧演绎人生：孩子犯错了怎么办？（冠男）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月20日 拥抱每一天- 智慧语录：但神的意思原是好的；神的叮咛我最爱：祂是主！（沈保罗牧师）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月21日 拥抱每一天- 拥抱小语：不同的态度，影响交友的结果（程枫）；复活节特辑：十架七言（一）施瑋。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月22日 拥抱每一天- 拥抱小语：聆听神的声音；复活节特辑：十架七言（二）施瑋。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月23日 拥抱每一天- 拥抱小语：耕耘与收获（程枫）；复活节特辑：十架七言（三）施瑋。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月24日 拥抱每一天- 拥抱小语：从自卑到广受欢迎；复活节特辑：十架七言（四）施瑋。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月25日 拥抱每一天- 拥抱小语：一个邮差的故事；复活节特辑：十架七言（五）施瑋。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月26日 拥抱每一天- 拥抱小语：敬意（白鹭）；复活节特辑：十架七言（六）施瑋。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月27日 拥抱每一天- 拥抱小语：鼓励；复活节特辑：十架七言（七）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月28日 拥抱每一天- 智慧语录：电学之父法拉第的几句话；拥抱小语：你的第二身份是什么？寻找生命的真光：丈夫外遇离婚后，我成了婚姻咨询师。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月29日 拥抱每一天- 智慧语录：成熟和淡定，才是中年之美；拥抱小语：走进对方的生命；千里思念万里情：属灵恩赐的配搭。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月30日 拥抱每一天- 智慧语录：正确的抉择是一生的必修课；拥抱小语：少年财主求永生；诗情细语话人生：样中小品。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年03月31日 拥抱每一天- 智慧语录：生活要的是质量；说个故事给你听：看别人比自己强。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjAzMzEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" }
];

var songs = JSON.parse(fs.readFileSync('ee2016_' + season + '_songs.json', 'utf8'));
songs.forEach(function(song, indexId) {


    song.title = titles[indexId].name;


});

fs.writeFile("./ee2016_" + season + "_songs_with_title.json", JSON.stringify(songs, null, '\t'));