const fs = require('fs');

var season = "autumn";

var titles = [
    { name: "15年07月01日 拥抱每一天- 智慧语录；拥抱小语；诗情细语话人生：济南的冬天、平凡最难。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月02日 拥抱每一天- 智慧语录；拥抱小语；说个故事给你听：除了爱，我一无所有。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月03日 拥抱每一天- 智慧语录；亮丽人生不是梦：在办公室里的愤怒。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月04日 拥抱每一天- 智慧语录；用智慧演绎人生：谈谈婚恋问题。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月05日 拥抱每一天- 智慧语录: 要学习认识自己；神的叮咛我最爱：你们要常在我的爱里。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月06日 拥抱每一天- 智慧语录：励志格言；拥抱小语：你们必须重生；寻找生命的真光：即兴发挥的人生注定痛苦。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月07日 拥抱每一天- 智慧语录：人这一辈子；拥抱小语：上帝的旨意你别问为什么？千里思念万里情：国民幸福指数的评估。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月08日 拥抱每一天- 智慧语录：上、中、下等人；拥抱小语：三篇小见证；诗情细语话人生：选择比天赋更重要。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月09日 拥抱每一天- 智慧语录：爱要珍惜，才会长久；拥抱小语：有三种钱，花的愈多，赚的愈多；说个故事给你听：活雷锋。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月10日 拥抱每一天- 亮丽人生不是梦：是什么使人产生扭曲的愤怒。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月11日 拥抱每一天- 智慧语录：品味；拥抱小语：人生的优先次序；用智慧演绎人生：十个最新的审美标准。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月12日 拥抱每一天- 智慧语录: 张爱玲的经典语录；神的叮咛我最爱：基督徒与世人的关系。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月13日 拥抱每一天- 发挥潜能，迈向成功（一）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月14日 拥抱每一天- 发挥潜能，迈向成功（二）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月15日 拥抱每一天- 发挥潜能，迈向成功（三）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月16日 拥抱每一天- 发挥潜能，迈向成功（四）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月17日 拥抱每一天- 发挥潜能，迈向成功（五）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月18日 拥抱每一天- 发挥潜能，迈向成功（六）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月19日 拥抱每一天- 智慧语录: 懂得，是一种难言的柔情；神的叮咛我最爱：主要差遣圣灵与我们同在。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月20日 拥抱每一天- 智慧语录：多少人输给了等待；拥抱小语：没有时间恨；寻找生命的真光：白人青年枪杀九个黑人之后。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月21日 拥抱每一天- 智慧语录：人生中要结交的四种朋友；拥抱小语：赶路客；千里思念万里情：神的主权与人的责任。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月22日 拥抱每一天- 智慧语录：牛顿对上帝的认识；拥抱小语：谈饶恕；诗情细语话人生：一位精英的临终感言。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月23日 拥抱每一天- 智慧语录：一个人的质量；拥抱小语：人生很多的可能性；说个故事给你听：考门夫人的见证。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月24日 拥抱每一天- 智慧语录：神所想的和我们所想的不一样；亮丽人生不是梦；谩骂和殴打。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月25日 拥抱每一天- 智慧语录；男人和女人的悲哀；拥抱小语：基督徒的工作态度；用智慧演绎人生：谈谈夫妻关系。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月26日 拥抱每一天- 智慧语录: 养好你的大气；神的叮咛我最爱：等不多时，你们要再见我。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月27日 拥抱每一天- 智慧语录：学会三句话，受用一辈子；拥抱小语：人类自己制造了一颗毒果；寻找生命的真光：美丽的心灵。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月28日 拥抱每一天- 智慧语录：谢谢我生命中出现的每一个你；拥抱小语：原配撞见了小三的孩子；千里思念万里情：万国丰收教会的教导是否正确？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月29日 拥抱每一天- 智慧语录：心情再差，也不要写在脸上；拥抱小语：爱迪生的信仰见证；诗情细语话人生：谷歌创始人在毕业典礼上的演讲（天路客）。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月30日 拥抱每一天- 智慧语录：成功是在行动中实现的；拥抱小语：有一种尊重叫守口如瓶；说个故事给你听：疼痛中的呼求与成长。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年07月31日 拥抱每一天- 智慧语录：做人之大忌；亮丽人生不是梦；压制愤怒的负面影响。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA3MzEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月01日 拥抱每一天- 智慧语录：人生八宝；拥抱小语：上帝给台湾首富王雪红的十堂课；用智慧演绎人生：欧洲人没有剩女。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月02日 拥抱每一天- 智慧语录: 快乐小贴士；神的叮咛我最爱：主耶稣受难前的祷告。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月03日 拥抱每一天- 智慧语录：做人与做事；拥抱小语：一切的遭遇都将成为安慰的力量；寻找生命的真光：同居时代战胜诱惑。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月04日 拥抱每一天- 智慧语录：全世界最牛的那些人是如何评价圣经的；拥抱小语：重用懂得感恩的人；千里思念万里情：再谈万国丰收教会的教导是否正确？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月05日 拥抱每一天- 智慧语录：人有教养的十大特征；拥抱小语：泰坦尼克号沉没事件的故事；诗情细语话人生：年轻；我打碎了一扇玻璃窗（天路客）。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月06日 拥抱每一天- 智慧语录：储蓄友谊；拥抱小语：坚不可摧；说个故事给你听：不要把时间和经历浪费在“恨”字上（商店店）。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月07日 拥抱每一天- 智慧语录：一生中值得我们交往的四类朋友；亮丽人生不是梦；上帝才是最终的审判者。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月08日 拥抱每一天- 用智慧演绎人生：再谈亲子关系。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月09日 拥抱每一天- 智慧语录:你是单位的草是家庭的天；神的叮咛我最爱：主从荣耀中降世，从世间回到荣耀中。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月10日 拥抱每一天- 智慧语录：你的人生规划了吗？；拥抱小语：有智慧数算自己的日子；寻找生命的真光：逃离郁悒的毒钩。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月11日 拥抱每一天- 智慧语录：世界名人对圣经的看法；拥抱小语：无声的尊重；千里思念万里情：论“美国同性婚姻合法化”。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月12日 拥抱每一天- 智慧语录：幸福的标志，你拥有几个？；拥抱小语：一个德国女人没有钱的富有人生；诗情细语话人生：谁来填补你的心；爱的礼物。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月13日 拥抱每一天- 智慧语录：生活是一面镜子；拥抱小语：给父母八个关键的教育指导；说个故事给你听：异国情缘。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月14日 拥抱每一天- 智慧语录：心怀感恩；亮丽人生不是梦；如何对待你受到的委屈。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月15日 拥抱每一天- 智慧语录：这样去工作会更出色：拥抱小语：别把纵容当宽恕；用智慧演绎人生：当爱与冲突发生时。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月16日 拥抱每一天- 智慧语录:永远不要看不起任何人；神的叮咛我最爱：主耶稣为历代信徒祷告。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月17日 拥抱每一天- 智慧语录：好的心态；寻找生命的真光：用一生来认识自己的残破。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月18日 拥抱每一天- 智慧语录：世界名人的信仰；拥抱小语：尽责；千里思念万里情：再论“同性婚姻”。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月19日 拥抱每一天- 智慧语录：发怒，是用别人的错误，来惩罚自己；拥抱小语：剑桥七杰的见证；诗情细语话人生：爱情，比我们想象中的更坚持。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月20日 拥抱每一天- 智慧语录：教养；拥抱小语：基督徒与人相处的误区；说个故事给你听：赵日安的心路历程。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月21日 拥抱每一天- 亮丽人生不是梦：用恩慈和友善对待那些伤害你的人。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月22日 拥抱每一天- 智慧语录：将被历史淘汰出局的人；用智慧演绎人生：如何在无爱的婚姻中获得幸福和满足。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月23日 拥抱每一天- 智慧语录:村上春树唯美的诗词；神的叮咛我最爱：主耶稣为属祂的人祷告。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月24日 拥抱每一天- 智慧语录：真正的朋友；拥抱小语：一指之遥的爱情；寻找生命的真光：你没读懂的鲁滨逊漂流记。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月25日 拥抱每一天- 智慧语录：做人要有厚度；拥抱小语：二个惊天大案对社会的影响；千里思念万里情：认识“福音派”。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月26日 拥抱每一天- 智慧语录：女人身上最浪漫的东西；诗情细语话人生：最后的爱；天堂鸟。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月27日 拥抱每一天- 智慧语录：做最好的自己；说个故事给你听：真正的丰盛。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月28日 拥抱每一天- 智慧语录：情商低的表现；亮丽人生不是梦：当你对配偶感到愤怒时。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月29日 拥抱每一天- 智慧语录：青年文摘语录；拥抱小语：迎接弥赛亚的国度；用智慧演绎人生：父母教育孩子的三大原则。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月30日 拥抱每一天- 智慧语录:不要拿小人的行为来惩罚自己；神的叮咛我最爱：主耶稣为信徒的合一祷告。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年08月31日 拥抱每一天- 智慧语录：林语堂的经典语录；拥抱小语：别让负面态度破坏你的人缘；寻找生命的真光：爱的绝唱：父亲和他的妻子。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA4MzEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月01日 拥抱每一天- 智慧语录：平和是一种为人的艺术；拥抱小语：好妻子与烂丈夫；千里思念万里情：宗教改革运动之分析。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月02日 拥抱每一天- 智慧语录：几句由衷的叮咛；拥抱小语：在最困难的时候，你会想到谁呢？诗情细语话人生：用爱点燃爱。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月03日 拥抱每一天- 智慧语录：做最好的自己；拥抱小语：恩典新数学；说个故事给你听：张延惠的生命故事。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月04日 拥抱每一天- 智慧语录：没有经历过失败的人生，不算是完美的人生；亮丽人生不是梦：寻求帮助是解决问题的第一步。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月05日 拥抱每一天- 智慧语录：爱一个人；拥抱小语：薪传就是传心；用智慧演绎人生：大龄单身不贱卖。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月06日 拥抱每一天- 智慧语录:人生极为重要的四个存折；神的叮咛我最爱：主耶稣求父保守众信徒脱离那恶者。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月07日 拥抱每一天- 寻找生命的真光：分手遇见爱。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月08日 拥抱每一天- 智慧语录：我很喜欢的几句话；拥抱小语：墙上的咖啡；千里思念万里情：福音派运动的完结篇。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月09日 拥抱每一天- 智慧语录：关心别人是一种真情；诗情细语话人生：大自然是最后的归宿吗？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月10日 拥抱每一天- 智慧语录：活在当下，且行且珍惜；拥抱小语：妈妈之歌；说个故事给你听：驱阴霾，庆新生。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月11日 拥抱每一天- 智慧语录：真正成功的人生；亮丽人生不是梦：当你对配偶感到愤怒时。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月12日 拥抱每一天- 智慧语录：邱吉尔的名言；拥抱小语：人生随时可以重来；用智慧演绎人生：妈妈，我从来不拿妳和别人做比较。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月13日 拥抱每一天- 智慧语录:最近很火的几句话你听过吗？；神的叮咛我最爱：求你用你的道使他们成圣。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月14日 拥抱每一天- 智慧语录：如果今天是我生命的最后一天；寻找生命的真光：尤妮斯的日记。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月15日 拥抱每一天- 特辑节目：特警大队长的精彩人生（一）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月16日 拥抱每一天- 特辑节目：特警大队长的精彩人生（二）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月17日 拥抱每一天- 特辑节目：特警大队长的精彩人生（三）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月18日 拥抱每一天- 特辑节目：特警大队长的精彩人生（四）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月19日 拥抱每一天- 智慧语录：好好的珍惜那些在很久以后你还会称为朋友的人；用智慧演绎人生：如何养好二个宝宝，让孩子的字典里没有偏心。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月20日 拥抱每一天- 智慧语录: 做个善良的人，你就会很幸福；神的叮咛我最爱：如何才能成圣？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月21日 拥抱每一天- 智慧语录：贾伯斯的遗言；拥抱小语：属灵小幽默；寻找生命的真光：被外在标准绑架的成功。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月22日 拥抱每一天- 智慧语录：成熟；拥抱小语：他救了669个孩子的生命，却不宣扬；千里思念万里情：新老年人。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月23日 拥抱每一天- 智慧语录：有一种心态叫放下；诗情细语话人生：论达文西密码。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月24日 拥抱每一天- 智慧语录：牛顿对上帝的认识；拥抱小语：不需要盐；说个故事给你听：黄立夫的信主见证", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月25日 拥抱每一天- 智慧语录：总会有人改变世界的，这个人可能就是你；亮丽人生不是梦：如何帮助孩子处理愤怒。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月26日 拥抱每一天- 智慧语录：时间，验证人心，见证人性；拥抱小语：话说头脑特工队；用智慧演绎人生：别养出“白眼狼”的孩子。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月27日 拥抱每一天- 智慧语录:上帝爱你的方式，其实你不知道；神的叮咛我最爱：我父所给我的那杯，我岂能不喝呢？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月28日 拥抱每一天- 智慧语录：简历和墓志铭，哪个更重要？；拥抱小语：不会被取代的东西；寻找生命的真光：谁是你的消防员？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月29日 拥抱每一天- 智慧语录：一个女人，一定要活得漂亮；拥抱小语：智慧的妻子；千里思念万里情：新老年人要学习“成功的老化”。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年09月30日 拥抱每一天- 智慧语录：不是因为…而是因为...；诗情细语话人生：美国流浪少女为何能进哈佛？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA5MzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" }
];

var songs = JSON.parse(fs.readFileSync('ee2015_' + season + '_songs.json', 'utf8'));
songs.forEach(function(song, indexId) {


    song.title = titles[indexId].name;


});

fs.writeFile("./ee2015_" + season + "_songs_with_title.json", JSON.stringify(songs, null, '\t'));