const fs = require('fs');

var season = "summer";

var titles = [
    { name: "15年04月01日 拥抱每一天- 复活节特辑：《使徒信经》对当代人的意义（八）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月02日 拥抱每一天- 复活节特辑：《使徒信经》对当代人的意义（九）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月03日 拥抱每一天- 复活节特辑：《使徒信经》对当代人的意义（十）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月04日 拥抱每一天- 复活节特辑：《使徒信经》对当代人的意义（十一）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月05日 拥抱每一天- 复活节特辑：《使徒信经》对当代人的意义（十二）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月06日 拥抱每一天- 智慧语录；拥抱小语；寻找生命的真光：初恋", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月07日 拥抱每一天- 智慧语录；拥抱小语；千里思念万里情：英雄造时势，光耀新加坡", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月08日 拥抱每一天- 智慧语录；拥抱小语；诗情细语话人生：清扫心灵的扫把", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月09日 拥抱每一天- 说个故事给你听：歌手黄美珍的故事", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月10日 拥抱每一天- 智慧语录；亮丽人生不是梦：安慰医治被迫害的人", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月11日 拥抱每一天- 关于龙的传说：起源于何处？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月12日 拥抱每一天- 智慧语录；神的叮咛我最爱：你们要彼此相爱", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月13日 拥抱每一天- 智慧语录；寻找生命的真光：你所不知道的安徒生童话", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月14日 拥抱每一天- 智慧语录；拥抱小语；千里思念万里情：在羊年谈羊", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月15日 拥抱每一天- 智慧语录；拥抱小语；诗情细语话人生：你爱我吗？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月16日 拥抱每一天- 智慧语录；拥抱小语；说个故事给你听：关心那些看起来在笑的人", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月17日 拥抱每一天- 智慧语录；亮丽人生不是梦：神如何处理迫害的原则", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月18日 拥抱每一天- 今晚，我们听书：恐龙如何灭绝？青春不叛逆", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月19日 拥抱每一天- 智慧语录；神的叮咛我最爱：怜恤体谅的爱", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月20日 拥抱每一天- 智慧语录；寻找生命的真光：小家伙不是弥赛亚", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月21日 拥抱每一天- 智慧语录；拥抱小语；千里思念万里情：从传媒谈诚信", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月22日 拥抱每一天- 智慧语录；拥抱小语；诗情细语话人生：这个世界有神吗？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月23日 拥抱每一天- 智慧语录；拥抱小语；说个故事给你听：90后Angel 的故事", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月24日 拥抱每一天- 智慧语录；亮丽人生不是梦：选择寻求神的话", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月25日 拥抱每一天- 今晚，我们听书：古代文明的典型特征；老爸的叮咛", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月26日 拥抱每一天- 智慧语录；神的叮咛我最爱：你是否有把握进入天家？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月27日 拥抱每一天- 智慧语录；寻找生命的真光：我和婆婆从仇敌到密友", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月28日 拥抱每一天- 智慧语录；拥抱小语；千里思念万里情：从圣经谈领导", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月29日 拥抱每一天- 智慧语录；拥抱小语；诗情细语话人生：80后写给90后毕业生的信", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年04月30日 拥抱每一天- 智慧语录；拥抱小语：安徒生童话中的基督信仰", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA0MzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月01日 拥抱每一天- 母亲节特辑：妈妈的爱：Angel 的故事", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月02日 拥抱每一天- 母亲节特辑：“妈妈的爱”：雨泽的故事", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月03日 拥抱每一天- 母亲节特辑：“妈妈的爱”：Sissi 的故事", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月04日 拥抱每一天- 母亲节特辑：“妈妈的爱”：武颖的故事", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月05日 拥抱每一天- 母亲节特辑：“妈妈的爱”：程枫的故事（一）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月06日 拥抱每一天- 母亲节特辑：“妈妈的爱”：程枫的故事（二）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月07日 拥抱每一天- 母亲节特辑：“妈妈的爱”：蔚立的故事（一）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月08日 拥抱每一天- 母亲节特辑：“妈妈的爱”：蔚立的故事（二）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月09日 拥抱每一天- 母亲节特辑：“妈妈的爱”：黄雯雯的故事", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月10日 拥抱每一天- 母亲节特辑：“妈妈的爱”：母爱创造的奇迹；母亲的手；母亲，世界因妳而美丽！", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月11日 拥抱每一天- 智慧语录；拥抱小语；寻找生命的真光：在信仰缺乏的时代，如何教养孩子？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月12日 拥抱每一天- 智慧语录；拥抱小语；千里思念万里情：为何圣经中的诗人也会咒诅敌人？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月13日 拥抱每一天- 智慧语录；拥抱小语；诗情细语话人生：和另一个女人约会；那人独居不好。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月14日 拥抱每一天- 智慧语录；拥抱小语；说个故事给妳听：打完了那美好的仗！", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月15日 拥抱每一天- 智慧语录；亮丽人生不是梦：愤怒--爱心的另一面。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月16日 拥抱每一天- 今晚，我们听书：《诸天述说》最初人类的能力如何？书籍介绍：密室。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月17日 拥抱每一天- 智慧语录：心无瀾，碧海蓝天；神的叮咛我最爱：你们奉我的名无论求什么，我必成就！", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月18日 拥抱每一天- 智慧语录；拥抱小语；寻找生命的真光：初恋。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月19日 拥抱每一天- 智慧语录；拥抱小语；千里思念万里情：大卫为何一错再错？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月20日 拥抱每一天- 智慧语录；拥抱小语；诗情细语话人生：一幅画、一个女孩的故事。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月21日 拥抱每一天- 智慧语录；拥抱小语；说个故事给妳听：失业之后。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月22日 拥抱每一天- 智慧语录；亮丽人生不是梦：爱的另一面：愤怒。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月23日 拥抱每一天- 智慧语录；拥抱小语；用智慧演绎人生：谈谈东西方的富二代。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月24日 拥抱每一天- 智慧语录；神的叮咛我最爱：主将圣灵赐给我们。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月25日 拥抱每一天- 智慧语录；拥抱小语；寻找生命的真光：你所不知道的安徒生童话。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月26日 拥抱每一天- 智慧语录；拥抱小语；千里思念万里情：基督信仰与民间信仰的会遇。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月27日 拥抱每一天- 智慧语录；拥抱小语；诗情细语话人生：穿着军服的天使，华盛顿的婚姻。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月28日 拥抱每一天- 智慧语录；拥抱小语；说个故事给妳听：郭莉的故事。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月29日 拥抱每一天- 智慧语录；亮丽人生不是梦：人际关系中的愤怒。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月30日 拥抱每一天- 智慧语录；拥抱小语；用智慧演绎人生：比惩罚更深刻的奖励。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年05月31日 拥抱每一天- 智慧语录；神的叮咛我最爱：我不撇下你们为孤儿。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA1MzEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月01日 拥抱每一天- 智慧语录；拥抱小语；寻找生命的真光：富二代的孤独很尴尬。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月02日 拥抱每一天- 智慧语录；拥抱小语；千里思念万里情：基督信仰与民间信仰的会遇（二）。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月03日 拥抱每一天- 智慧语录；拥抱小语；诗情细语话人生：幸福很近；我不是一个悲惨的故事。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月04日 拥抱每一天- 智慧语录；拥抱小语；说个故事给妳听：野地的花。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月05日 拥抱每一天- 智慧语录；亮丽人生不是梦：克制自己。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月06日 拥抱每一天- 智慧语录；拥抱小语；用智慧演绎人生：圣经中魅力非凡的25位女性。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月07日 拥抱每一天- 智慧语录；神的叮咛我最爱：圣灵要将一切的事指教你们。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月08日 拥抱每一天- 智慧语录；拥抱小语；寻找生命的真光：小心掉入品格教育。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月09日 拥抱每一天- 智慧语录；拥抱小语；千里思念万里情：悔过自新的父亲形象。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月10日 拥抱每一天- 智慧语录；拥抱小语；诗情细语话人生：我比爸爸先认识妈妈。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月11日 拥抱每一天- 智慧语录；拥抱小语；说个故事给妳听：繁花尽处皆美景。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月12日 拥抱每一天- 智慧语录；亮丽人生不是梦：忍耐，有时候就是最好的处理。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月13日 拥抱每一天- 父亲节特辑：爸爸的爱：许承仁的故事", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月14日 拥抱每一天- 父亲节特辑：爸爸的爱：林凤梅的故事。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月15日 拥抱每一天- 父亲节特辑：爸爸的爱：圣慧、张兴园的故事。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月16日 拥抱每一天- 父亲节特辑：爸爸的爱：范宝炘的故事。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月17日 拥抱每一天- 父亲节特辑：爸爸的爱：范宝炘的故事。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月18日 拥抱每一天- 父亲节特辑：爸爸的爱：周胜琼的故事。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月19日 拥抱每一天- 父亲节特辑：爸爸的爱：夏安平的故事。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月20日 拥抱每一天- 父亲节特辑：爸爸的爱：李秀丽的故事", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月21日 拥抱每一天- 父亲节特辑：爸爸的爱：庄泽丰牧师。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月22日 拥抱每一天- 智慧语录；拥抱小语；寻找生命的真光：投资天国的股票。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月23日 拥抱每一天- 智慧语录；拥抱小语；千里思念万里情：基督信仰与民间宗教的会遇（三）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月24日 拥抱每一天- 智慧语录；拥抱小语；诗情细语话人生：你杀我全家，我活你全村。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月25日 拥抱每一天- 智慧语录；拥抱小语；说个故事给你听：乌云背后有蓝天。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月26日 拥抱每一天- 智慧语录；亮丽人生不是梦：扭曲的愤怒。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月27日 拥抱每一天- 智慧语录；拥抱小语；用智慧演绎人生：厚道父母如何毁了我的一生。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月28日 拥抱每一天- 智慧语录；神的叮咛我最爱：要做多结果子的枝子。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月29日 拥抱每一天- 智慧语录；拥抱小语；寻找生命的真光：富人想做好人容易吗？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年06月30日 拥抱每一天- 智慧语录；拥抱小语；千里思念万里情：基督信仰与民间宗教的会遇（四）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTA2MzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" }
];

var songs = JSON.parse(fs.readFileSync('ee2015_' + season + '_songs.json', 'utf8'));
songs.forEach(function(song, indexId) {


    song.title = titles[indexId].name;


});

fs.writeFile("./ee2015_" + season + "_songs_with_title.json", JSON.stringify(songs, null, '\t'));