const fs = require('fs');

var season = "summer";

var titles = [
    { name: "17年04月01日 拥抱每一天- 智慧语录：让幸福相伴相随；拥抱小语：你就是那支铅笔；神的叮咛我最爱：怎样以好行为来宣扬基督。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月02日 拥抱每一天- 智慧语录：别去打扰一个不理你的人；拥抱小语：祷告是基督徒的属灵呼吸；神的叮咛我最爱：过客人生。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月03日 拥抱每一天- 智慧语录：人到中年应该明白的事；拥抱小语：一个误了几代人的故事；寻找生命的真光：辞去8年工作，当个全职妈妈，我不后悔。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月04日 拥抱每一天- 绽放生命的光芒：生命真正的价值。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月05日 拥抱每一天- 智慧语录：活得轻松，老得漂亮；诗情细语话人生：别忘了你心中的那只老虎。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月06日 拥抱每一天- 复活节特辑：说个故事给你听（一）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月07日 拥抱每一天- 复活节特辑：说个故事给你听（二）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月08日 拥抱每一天- 复活节特辑：说个故事给你听（三）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月09日 拥抱每一天- 拥抱小语：爱你的仇敌；复活节特辑：说个故事给你听（四）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月10日 拥抱每一天- 复活节特辑：说个故事给你听（五）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月11日 拥抱每一天- 复活节特辑：说个故事给你听（六）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月12日 拥抱每一天- 拥抱小语：上帝的恩典；复活节特辑：说个故事给你听（七）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月13日 拥抱每一天- 复活节特辑：说个故事给你听（八）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月14日 拥抱每一天- 智慧语录：你称我为主，你听从我了吗？；拥抱小语：从己所不欲勿施于人到黄金法则；复活节特辑：说个故事给你听（九）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月15日 拥抱每一天- 复活节特辑：说个故事给你听（十）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月16日 拥抱每一天- 智慧语录：聆听神的声音；拥抱小语：爱在生命中起了多大的作用；复活节特辑：说个故事给你听（十一）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月17日 拥抱每一天- 智慧语录：你的人生格局是大是小呢？拥抱小语：宽容；寻找生命的真光：从虎口被替代下来的女儿。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月18日 拥抱每一天- 绽放生命的光芒：爱不是我们要去的地方，而是我们出发的地方。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月19日 拥抱每一天- 智慧语录：当你看透一切时；拥抱小语：为什么有些姑娘的人生像是开了挂；诗情细语话人生：我的基督徒老板。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月20日 拥抱每一天- 智慧语录：这辈子，应该铭记在心的人；拥抱小语：有孩子的夫妻，离婚要慎重；说个故事给你听：当基督徒住进这栋公寓楼。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月21日 拥抱每一天- 智慧语录：自己不坚强，没人能代替；拥抱小语：母爱无声；亮丽人生不是梦：理想的自我应该服从真实的自我。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月22日 拥抱每一天- 智慧语录：把人生过得轻轻松松；拥抱小语：一日夫妻百日恩；用智慧演绎人生：烈火先知亦需要处世常识。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月23日 拥抱每一天- 智慧语录：这样读诗篇23篇，让我啼笑皆非；拥抱小语：当冷漠成为一种习惯；神的叮咛我最爱：客旅人生。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月24日 拥抱每一天- 智慧语录：让孩子结交这七位朋友；拥抱小语：手机与上帝的对话；寻找生命的真光：轮椅上自由的小鸟。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月25日 拥抱每一天- 绽放生命的光芒：当代年轻人追求真理的轨迹。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月26日 拥抱每一天- 智慧语录：夫妻就像一双鞋；拥抱小语：捡起老公的臭袜子；诗情细语话人生：任何人都会变老，但不是每个人都会成长。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月27日 拥抱每一天- 拥抱小语：苦毒的重担；说个故事给你听：苦难来临，我在恩典中重生。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月28日 拥抱每一天- 智慧语录：把骄傲放在一边，学会真诚的道歉；拥抱小语：上帝看人和人看人有何不同；亮丽人生不是梦：爱与接纳。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月29日 拥抱每一天- 智慧语录：聪明与智慧；拥抱小语：耶稣专题片；用智慧演绎人生：性格内向的人，如何搞好人际关系？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年04月30日 拥抱每一天- 拥抱小语：我要这样死去；神的叮咛我最爱：跟随基督的脚踪行。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA0MzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月01日 拥抱每一天- 智慧语录：人格，是做人的品牌；寻找生命的真光：服侍老年痴呆症的80后。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月02日 拥抱每一天- 绽放生命的光芒：把孩子培养成有魅力的普通人。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月03日 拥抱每一天- 母亲节特辑《与幸福有约》：为你做牛做马的女人就是妈，你怎能不爱她；母亲，妳是我整个的世界；在当妈之前，我首先是个女人。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月04日 拥抱每一天- 母亲节特辑《与幸福有约》：妈妈，当我哭泣时，请给我肩膀；妈妈也是第一次当妈妈；妈妈，妳温柔吗？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月05日 拥抱每一天- 母亲节特辑《与幸福有约》：妈妈，我愿不惜一切保护妳；你是妈妈的天使。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月06日 拥抱每一天- 母亲节特辑《与幸福有约》：母亲的缝纫机；培养出五个牧师的母亲；母亲的力量。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月07日 拥抱每一天- 母亲节特辑《与幸福有约》：窗上的把手可以抓吗；母亲的四季。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月08日 拥抱每一天- 母亲节特辑《与幸福有约》：妈妈会做，才是家庭的幸福；仁厚的母亲。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月09日 拥抱每一天- 母亲节特辑《与幸福有约》：一句话影响了孩子的一生；母亲的宝物；母爱创造的奇迹。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月10日 拥抱每一天- 母亲节特辑《与幸福有约》：如何和父母相处不抓狂；没有上锁的母爱。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月11日 拥抱每一天- 母亲节特辑《与幸福有约》：培养孩子快乐的能力（一）自制的能力；别把妈妈埋进坑里。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月12日 拥抱每一天- 母亲节特辑《与幸福有约》：真正的好家庭，一定是拼妈的；培养孩子承受失败的能力。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月13日 拥抱每一天- 母亲节特辑《与幸福有约》：智慧的女人，幸福的家；培养孩子独立的能力。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月14日 拥抱每一天- 母亲节特辑《与幸福有约》：母亲是一种岁月；母亲的手；培养孩子忍耐的能力。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月15日 拥抱每一天- 智慧语录：你的心态，决定你的人生；寻找生命的真光：小别离，不叛逆。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月16日 拥抱每一天- 绽放生命的光芒：清教徒留给我们的九大信仰财富。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月17日 拥抱每一天- 智慧语录：父母在，常回家；拥抱小语：心之所系，家之所在；诗情细语话人生：在苦难中感恩。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月18日 拥抱每一天- 智慧语录：人的一生，一定要用宽容之心原谅的三个人；拥抱小语：把你的重担卸给神；说个故事给你听：戴德生的信心见证。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月19日 拥抱每一天- 智慧语录：一个人在不在乎你，一看便知；拥抱小语：选老公，这一点比人品更重要；亮丽人生不是梦：面对世界的善与恶。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月20日 拥抱每一天- 智慧语录：会对你有帮助的几句话；拥抱小语：父母经常吵架的孩子，长大后都活成什么样；最好的修养是明知不问。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月21日 拥抱每一天- 智慧语录：基督徒婚姻十诫；拥抱小语：人不离开父母，就难有幸福的婚姻；神的叮咛我最爱：跟随基督的脚踪。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月22日 拥抱每一天- 严冬之后有春天（一）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月23日 拥抱每一天- 严冬之后有春天（二）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月24日 拥抱每一天- 严冬之后有春天（三）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月25日 拥抱每一天- 严冬之后有春天（四）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月26日 拥抱每一天- 严冬之后有春天（五）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月27日 拥抱每一天- 严冬之后有春天（六）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月28日 拥抱每一天- 智慧语录：如果要结婚，请牢记这几句话；拥抱小语：当女人想成为女强人；神的叮咛我最爱：幸福婚姻中的好丈夫。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月29日 拥抱每一天- 智慧语录：不在乎你的人，请你放下他；寻找生命的真光：为什么我会如此焦虑？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月30日 拥抱每一天- 绽放生命的光芒：如何做个好妻子--成为丈夫荣耀的帮助者。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年05月31日 拥抱每一天- 智慧语录：大智若愚的处世之道；拥抱小语：你和上帝的关系是否浅薄？；诗情细语话人生：幸福在平淡中活出精彩。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA1MzEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月01日 拥抱每一天- 智慧语录：要学会一个人走，不管有没有人陪；拥抱小语：致在黑夜辗转难眠的人；说个故事给你听：美国的诗歌圣徒芬妮克罗斯比。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月02日 拥抱每一天- 智慧语录：话有三不说；拥抱小语：背起自己的壳；亮丽人生不是梦：过度的愤怒。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月03日 拥抱每一天- 智慧语录：人有三不交；拥抱小语：告诉孩子，能说谢谢时，就不要说对不起；用智慧演绎人生：别让说话暴露了你的幼稚。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月04日 拥抱每一天- 智慧语录：信任毁了，感情就没了；拥抱小语：聊不到一起的感情，终究走不远；神的叮咛我最爱：幸福婚姻中的好妻子。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月05日 拥抱每一天- 智慧语录：让步；寻找生命的真光：从女记者因男友婚前出轨自杀谈起。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月06日 拥抱每一天- 绽放生命的光芒：一家人里的那些事。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月07日 拥抱每一天- 智慧语录：借钱见人心，还钱见人品；拥抱小语：十种方法助你远离性试探；诗情细语话人生：态度，人生的选择之一。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月08日 拥抱每一天- 智慧语录：一辈子真的好难；拥抱小语：永不放弃；说个故事给你听：浪子终于回家。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月09日 拥抱每一天- 智慧语录：深交五种朋友，远离四种人；拥抱小语：好朋友；亮丽人生不是梦：解决善恶问题的障碍。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月10日 拥抱每一天- 智慧语录：几句话，送给身处困境的朋友；拥抱小语：先见神的国；用智慧演绎人生：孩子网络上瘾该怎么办？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月11日 拥抱每一天- 父亲节特辑（—）：如果我能再次养大我的孩子；父亲的缺位；七种具有杀伤力的爸爸。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月12日 拥抱每一天- 父亲节特辑（二）：父亲，这个时代的稀缺品；别在孩子心中留下空洞；把爸爸捐出去吧！", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月13日 拥抱每一天- 父亲节特辑（三）：男人最大的时尚；父亲有趣，是家庭的幸运；一位爸爸嫁女儿的致词；爸爸和儿子幽默的对话。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月14日 拥抱每一天- 父亲节特辑（四）：我多想有个能依靠的爸爸；马修父亲写给儿子的信。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月15日 拥抱每一天- 父亲节特辑（五）：爸爸，你生气的样子真可怕；拿什么来爱你，我的爸爸。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月16日 拥抱每一天- 父亲节特辑（六）：好爸爸是家里的一束光；父亲的声音。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月17日 拥抱每一天- 父亲节特辑（七）：父亲的影响力！", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月18日 拥抱每一天- 父亲节特辑（八）：再见，晓华；我很爱你，但你不是世界的中心；父亲与准备离婚的儿子的对话。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月19日 拥抱每一天- 智慧语录：说不出的伤，最痛；寻找生命的真光：我与战争中的孩子，有同样的心碎。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月20日 拥抱每一天- 绽放生命的光芒：以非凡之爱做平凡之事：万婴之母、生命天使林巧稚医生的故事。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月21日 拥抱每一天- 智慧语录：容言容事容人；拥抱小语：一个拾荒老人；诗情细语话人生：一颗核桃树。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月22日 拥抱每一天- 智慧语录：做人精三分、傻三分、留下三分给子孙；拥抱小语：欲望是最深的陷阱；说个故事给你听：患MDS-RA慢性血液病的女孩。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月23日 拥抱每一天- 智慧语录：感恩是一种生活态度；拥抱小语：做父母的有效期；亮丽人生不是梦：真我与理想之间的我的关系。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月24日 拥抱每一天- 智慧语录：不要让不好意思，成为你人生的绊脚石；拥抱小语：高情商的男人令你多舒服；用智慧演绎人生：先管理再领导。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月25日 拥抱每一天- 智慧语录：原谅所有的人和事；拥抱小语：懂得拐弯，才是人生的大智慧；神的叮咛我最爱：职场上的顺服。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月26日 拥抱每一天- 智慧语录：在困境时对你有帮助的几句话；寻找生命的真光：我的婚姻复活了！", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月27日 拥抱每一天- 绽放生命的光芒：哈佛毕业生、年薪百万的世界顶级银行总裁，对艾滋病患者的拥抱救助。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月28日 拥抱每一天- 智慧语录：女人一生该坚持的东西；拥抱小语：平安的滋味；诗情细语话人生：你会做出同样的选择吗？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月29日 拥抱每一天- 智慧语录：几句话，送给所有的夫妻；拥抱小语：做人一定要有诚信；说个故事给你听：脱下抑郁的黑丧服。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "17年06月30日 拥抱每一天- 智慧语录：女人相守，男人感恩，才是一辈子；拥抱小语：诚实与成功；亮丽人生不是梦。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvZWUvZWUxNzA2MzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" }
];

var songs = JSON.parse(fs.readFileSync('ee2017_' + season + '_songs.json', 'utf8'));
songs.forEach(function(song, indexId) {


    song.title = titles[indexId].name;


});

fs.writeFile("./ee2017_" + season + "_songs_with_title.json", JSON.stringify(songs, null, '\t'));