const fs = require('fs');

var season = "winter";

var titles = [
    { name: "15年10月01日 拥抱每一天- 特别节目：希望总在转角处，生命不可轻放弃（1）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月02日 拥抱每一天- 特别节目：希望总在转角处，生命不可轻放弃（2）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月03日 拥抱每一天- 特别节目：希望总在转角处，生命不可轻放弃（3）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月04日 拥抱每一天- 特别节目：希望总在转角处，生命不可轻放弃（4）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月05日 拥抱每一天- 特别节目：希望总在转角处，生命不可轻放弃（5）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月06日 拥抱每一天- 特别节目：希望总在转角处，生命不可轻放弃（6）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月07日 拥抱每一天- 特别节目：希望总在转角处，生命不可轻放弃（7）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月08日 拥抱每一天- 智慧语录：当你老了；拥抱小语：如何遇见对的他；说个故事给你听：方莉的日记。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月09日 拥抱每一天- 智慧语录：内心强大的人；亮丽人生不是梦：当你对上帝感到愤怒时。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月10日 拥抱每一天- 智慧语录：不要让自己迷失方向；拥抱小语：马云的老婆，值得每个女性看看；用智慧演绎人生：爱中的话题。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月11日 拥抱每一天- 智慧语录：做人，要对得起别人的善良和信任；神的叮咛我最爱：贪财是万恶之根。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月12日 拥抱每一天- 智慧语录：多一份包容，就少一份争执；拥抱小语：你常和神独处吗？寻找生命的真光：中国式聪明可以改变吗？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月13日 拥抱每一天- 智慧语录：在给予中快乐，在简单中幸福；拥抱小语：男人一生最好的投资；千里思念万里情：胎儿的生命权。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月14日 拥抱每一天- 智慧语录：包容越多，幸福越多；诗情细语话人生：评蜗居：自私使男人失去责任。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月15日 拥抱每一天- 智慧语录：一个女人的幸福；拥抱小语：请对最亲密的人保持尊重和耐心；说个故事给你听：只有爱能建造幸福家庭。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月16日 拥抱每一天- 智慧语录：要拥有美满的婚姻，以下类型的异性，请你别碰；亮丽人生不是梦：我生我自己的气，那该怎么办？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月17日 拥抱每一天- 智慧语录：随和；拥抱小语：我回归基督了--林语堂的故事；用智慧演绎人生：儿童做家务年龄表。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月18日 拥抱每一天- 智慧语录：在你心中一定要有一座山；神的叮咛我最爱：当保守我们的心，胜过保守一切。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月19日 拥抱每一天- 智慧语录：能伤你心的，都是你在乎的人；寻找生命的真光：我们可能都是精神病人。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月20日 拥抱每一天- 智慧语录：对每个人不要轻易的发脾气；拥抱小语：离婚不是唯一的选择；千里思念万里情：安享余闲。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月21日 拥抱每一天- 智慧语录：自卑，是用别人的长处诋毁自己；诗情细语话人生：评蜗居：利益，使社会失去秩序。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月22日 拥抱每一天- 智慧语录：妳是女人，妳得为自己漂亮的活着；拥抱小语：有趣，是一种软实力；说个故事给你听：方莉的日记。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月23日 拥抱每一天- 智慧语录：如果我能再次养大我的孩子；亮丽人生不是梦：原谅自己。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月24日 拥抱每一天- 用智慧演绎人生：七种让宝宝更加聪明的方法。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月25日 拥抱每一天- 智慧语录：让步的男人才是最可交的男人；神的叮咛我最爱：要靠圣灵做个刚强的人。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月26日 拥抱每一天- 智慧语录：李嘉诚的“做事必须搞清10顺序”；寻找生命的真光：独一无二的《小王子》与我。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月27日 拥抱每一天- 智慧语录：今天再大的事，到了明天就是小事；拥抱小语：假如今天是我生命的最后一天；千里思念万里情：月亮代表我的心。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月28日 拥抱每一天- 智慧语录：人生，就是要坚强的去面对；诗情细语话人生：车票。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月29日 拥抱每一天- 智慧语录：每天七件事，牵着幸福一起走；拥抱小语：神的心意和目的；说个故事给你听：不让我的眼泪陪我过夜。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月30日 拥抱每一天- 智慧语录：有没有一个人这样宠你？；亮丽人生不是梦：假如你碰到一个愤怒的人该怎么办？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年10月31日 拥抱每一天- 智慧语录：人格如金；用智慧演绎人生：请鼓励你的孩子做一个幸福的普通人。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEwMzEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月01日 拥抱每一天- 特辑节目：不甘平庸，追求卓越！（一）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月02日 拥抱每一天- 特辑节目：不甘平庸，追求卓越！（二）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月03日 拥抱每一天- 特辑节目：不甘平庸，追求卓越！（三）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月04日 拥抱每一天- 特辑节目：不甘平庸，追求卓越！（四）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月05日 拥抱每一天- 特辑节目：不甘平庸，追求卓越！（五）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月06日 拥抱每一天- 特辑节目：不甘平庸，追求卓越！（六）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月07日 拥抱每一天- 特辑节目：不甘平庸，追求卓越！（七）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月08日 拥抱每一天- 特辑节目：不甘平庸，追求卓越！（八）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月09日 拥抱每一天- 智慧语录：做好你自己，活出生命的价值；拥抱小语：如何避免家庭不和；寻找生命的真光：拿什么拯救你，80后的婚姻。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月10日 拥抱每一天- 智慧语录：当你...上帝说……；拥抱小语：莫将人生全部外包；千里思念万里情：研究旧约圣经对当代人有何意义？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月11日 拥抱每一天- 智慧语录：以下的好习惯，你拥有几个？诗情细语话人生：牵手的习惯。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月12日 拥抱每一天- 智慧语录：跟对人，走对路，做对事；说个故事给你听：方莉的日记。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月13日 拥抱每一天- 智慧语录：遇见自己；亮丽人生不是梦：改变带来医治。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月14日 拥抱每一天- 智慧语录：我选择这样做人，你呢？拥抱小语：古代母教的智慧；用智慧演绎人生：母亲的性格、言语和行为，会影响孩子的一生。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月15日 拥抱每一天- 智慧语录：托尔斯泰的心路历程；神的叮咛我最爱：人性破产唯一的希望。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月16日 拥抱每一天- 智慧语录：为什么这些人一开始是个笑话，后来却成为神话呢？；寻找生命的真光：为病人祷告的医生钟爱华。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月17日 拥抱每一天- 智慧语录：每个人的路，都得自己走；拥抱小语：原来人生可以很简单；千里思念万里情：研读圣经的瓶颈。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月18日 拥抱每一天- 智慧语录：当你扛不住的时候，送你几句话；诗情细语话人生：只剩下我的灵魂。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月19日 拥抱每一天- 智慧语录：读人、品人、悟人、做人；拥抱小语：双重的款待；说个故事给你听：苦难中神信实的呼召。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月20日 拥抱每一天- 智慧语录：不忘初心，方得始终；亮丽人生不是梦：成长的三个因素。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月21日 拥抱每一天- 智慧语录：世间真正的高手；拥抱小语：你最重要的是什么；用智慧演绎人生：成为好妈妈的十条秘诀。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月22日 拥抱每一天- 智慧语录：儿童教育的重要性；神的叮咛我最爱：我的国不属这个世界。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月23日 拥抱每一天- 感恩节特别节目：感谢生命中有你；基督徒要不要过感恩节；黑暗中的舞者--在苦难中的感恩。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月24日 拥抱每一天- 感恩节特别节目：我的心啊，你要称颂耶和华；林肯的感恩节宣言；美国感恩节对我们的影响。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月25日 拥抱每一天- 感恩节特别节目：要感谢你身边的人；感恩节快乐感恩；感谢生命的美意。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月26日 拥抱每一天- 感恩节特别节目：亲爱的，祝你感恩节快乐；一群失败者为什么还要感恩？；话说感恩节。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月27日 拥抱每一天- 智慧语录：男人最大的时尚；拥抱小语：彩色的应许；亮丽人生不是梦：真理若是缺了恩典。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月28日 拥抱每一天- 智慧语录：做人的最高意境；拥抱小语：神掌管前程；用智慧演绎人生：家长一定要给孩子的礼物。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月29日 拥抱每一天- 智慧语录：生活中应该培养的好习惯；神的叮咛我最爱：十字架是我的荣耀。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年11月30日 拥抱每一天- 智慧语录：让人生豁然开朗的几句话；拥抱小语：追求卓越不是梦；寻找生命的真光：改变自己到底有多难。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTExMzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月01日 拥抱每一天- 特辑节目：不甘平庸，追求卓越（9）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月02日 拥抱每一天- 特辑节目：不甘平庸，追求卓越（10）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月03日 拥抱每一天- 特辑节目：不甘平庸，追求卓越（11）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月04日 拥抱每一天- 特辑节目：不甘平庸，追求卓越（12）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月05日 拥抱每一天- 特辑节目：不甘平庸，追求卓越（13）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月06日 拥抱每一天- 特辑节目：不甘平庸，追求卓越（14）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月07日 拥抱每一天- 特辑节目：不甘平庸，追求卓越（15）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月08日 拥抱每一天- 特辑节目：不甘平庸，追求卓越（16）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月09日 拥抱每一天- 智慧语录：放自己一条生路；诗情细语话人生：是谁杀死托尔斯泰的爱情？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月10日 拥抱每一天- 智慧语录：能认真洗衣做饭的人，都能自带光芒；拥抱小语：伸出援手; 说个故事给你听：方莉的日记。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月11日 拥抱每一天- 智慧语录：做人六个不要；拥抱小语：当亿万富翁的儿子遇上了农村的孩子；亮丽人生不是梦：恩典与真理。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月12日 拥抱每一天- 智慧语录：交朋友的标准是什么？拥抱小语：不是人不行，是制度不行；用智慧演绎人生：德国的父母是怎样教育孩子的。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月13日 拥抱每一天- 智慧语录：圣经教你做事做人；神的叮咛我最爱：他究竟是谁？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月14日 拥抱每一天- 智慧语录：给年轻朋友的几句话；拥抱小语：世界上最宝贵的玫瑰；寻找生命的真光：巴黎一夜。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月15日 拥抱每一天- 智慧语录：心简单，世界就简单；拥抱小语：梵高画中的基督；千里思念万里情：如何突破读经的瓶颈。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月16日 拥抱每一天- 智慧语录：哈佛推荐的快乐习惯；诗情细语话人生：如果我欠你五块钱，请你直接告诉我。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月17日 拥抱每一天- 智慧语录：哈佛推荐的快乐习惯；拥抱小语：不信神的借口; 说个故事给你听：出旷野入迦南。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月18日 拥抱每一天- 智慧语录：让你快乐的好习惯；拥抱小语：仿佛世界都变回最纯真的样子；亮丽人生不是梦：罪恶感的障碍。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月19日 拥抱每一天- 智慧语录：真正对你好的人，应该是这样的；拥抱小语：求福、得福、享福；用智慧演绎人生：让孩子做作业如飞的妙招。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月20日 拥抱每一天- 智慧语录：醒来，每一天都这么美好；神的叮咛我最爱：不求自保卖良知。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月21日 拥抱每一天- 智慧语录：茫茫人海，有种关系不可替代；拥抱小语：上帝给你的，一定是最合适的；寻找生命的真光：回到上帝的坐标。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月22日 拥抱每一天- 圣诞特别节目：《平安夜》背后的温馨故事；在美国过圣诞节。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月23日 拥抱每一天- 圣诞特别节目：广播剧：圣诞的蜡烛；基督徒艺人周慧敏信主的见证。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月24日 拥抱每一天- 圣诞特别节目：广播剧：圣诞的更新；如果耶稣没有来过这个世界；圣诞节的由来。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月25日 拥抱每一天- 圣诞特别节目：广播剧：最好的消息；惊喜圣诞夜。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月26日 拥抱每一天- 智慧语录：婚姻，到底给了女人什么？；拥抱小语：别让快舌毁了你：用智慧演绎人生：人的一生只有五天。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月27日 拥抱每一天- 智慧语录：你所在意的到底是什么？神的叮咛我最爱：耶稣摧毁了死亡的权势。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月28日 拥抱每一天- 智慧语录：做人貴于清醒坦诚，做事貴于聪明智慧；拥抱小语：双目失明却画出最美的色彩；寻找生命的真光：别怕孩子看见真实的父母。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月29日 拥抱每一天- 智慧语录：以前我错了，现在我懂了；拥抱小语：你追求的是幸福还是幸福感？千里思念万里情：面向新年新期许。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月30日 拥抱每一天- 智慧语录：得体比好看重要得多了；诗情细语话人生：一颗土豆的幸福；命运的第二次机会。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "15年12月31日 拥抱每一天- 智慧语录：积极面向新的一年；拥抱小语：告别旧岁，拥抱新年；说个故事给你听：方莉的日记。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNTEyMzEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" }
];

var songs = JSON.parse(fs.readFileSync('ee2015_' + season + '_songs.json', 'utf8'));
songs.forEach(function(song, indexId) {


    song.title = titles[indexId].name;


});

fs.writeFile("./ee2015_" + season + "_songs_with_title.json", JSON.stringify(songs, null, '\t'));