const fs = require('fs');

var season = "summer";

var titles = [
    { name: "16年04月01日 拥抱每一天- 智慧语录：你，是一切的根源；拥抱小语：是谁定义了我的幸福；亮丽人生不是梦：相连的障碍。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月02日 拥抱每一天- 智慧语录：伟人们的共同特质；用智慧演绎人生：再大的成功，也弥补不了教育子女失败的遗憾。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月03日 拥抱每一天- 智慧语录：不同年龄段的取舍；神的叮咛我最爱：你爱我吗？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月04日 拥抱每一天- 智慧语录：朋友是一辈子的财富；拥抱小语：你活下去的理由是什么？寻找生命的真光：拿什么来爱你，我的爸爸！", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月05日 拥抱每一天- 智慧语录：真实的活着；拥抱小语：打破的杯子；千里思念万里情：祷告的功课。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月06日 拥抱每一天- 智慧语录：如果你50几岁了；拥抱小语：献给想出轨和正在出轨的人；诗情细语话人生：天使与出发。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月07日 拥抱每一天- 说个故事给你听：黑帮老大洪汉义的救赎人生。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月08日 拥抱每一天- 智慧语录：送给在感情路上深受伤害的朋友；亮丽人生不是梦：如何与人相连。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月09日 拥抱每一天- 智慧语录：和什么样的人在一起，真的很重要；拥抱小语：从红杉树学习生命成长的功课；用智慧演绎人生：如果你忍不住对孩子发火时。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月10日 拥抱每一天- 特辑节目：展翅飞扬的人生（一）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月11日 拥抱每一天- 特辑节目：展翅飞扬的人生（二）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月12日 拥抱每一天- 特辑节目：展翅飞扬的人生（三）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月13日 拥抱每一天- 特辑节目：展翅飞扬的人生（四）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月14日 拥抱每一天- 特辑节目：展翅飞扬的人生（五）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月15日 拥抱每一天- 特辑节目：展翅飞扬的人生（六）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月16日 拥抱每一天- 特辑节目：展翅飞扬的人生（七）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月17日 拥抱每一天- 特辑节目：展翅飞扬的人生（八）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月18日 拥抱每一天- 特辑节目：展翅飞扬的人生（九）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月19日 拥抱每一天- 智慧语录：成功是什么？拥抱小语：领导力的关键；千里思念万里情：清心的人才能见到上帝。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月20日 拥抱每一天- 智慧语录：懂不懂得？拥抱小语：祂是我们最棒的大英雄；诗情细语话人生：不要珍藏去等待不确定的日子。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月21日 拥抱每一天- 智慧语录：成熟男人的生命内涵；拥抱小语：丈夫--一家之主；说个故事给你听：一个美丽的姑娘就这样离开了。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月22日 拥抱每一天- 智慧语录：包容越多，幸福越多；拥抱小语：世界上最长的路；亮丽人生不是梦：当我们不能与人相连时。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月23日 拥抱每一天- 智慧语录：别再难为自己；拥抱小语：不得不认真的问题；谈谈如何表扬你的孩子。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月24日 拥抱每一天- 智慧语录：人，不可不圆，但不可太圆；神的叮咛我最爱：一生跟随，永不离开！", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月25日 拥抱每一天- 智慧语录：决定孩子一生的，不是成绩，而是健全的品格；拥抱小语：请尊重每一个平凡人的努力；寻找生命的真光：爱生命，即要爱其柔弱。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月26日 拥抱每一天- 智慧语录：成为一名有教养的女人；千里思念万里情：只见耶稣。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月27日 拥抱每一天- 智慧语录：简简单单几个字，一辈子学不完；拥抱小语：恩典与深层偶像；诗情细语话人生：别了，花花世界。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月28日 拥抱每一天- 智慧语录：做人，不要玩心眼；拥抱小语：平衡家庭与事业的谎言；说个故事给你听：从头爱到尾。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月29日 拥抱每一天- 智慧语录：俄罗斯的小诗；拥抱小语：铁汉的眼泪；亮丽人生不是梦：当我们不能与人相连时。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年04月30日 拥抱每一天- 智慧语录：有些人有些事，真的会来不及；拥抱小语：保持连线；用智慧演绎人生：该不该带着孩子去旅游。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA0MzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月01日 拥抱每一天- 母亲节特辑：只有母爱，不言放弃！（一）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月02日 拥抱每一天- 母亲节特辑：只有母爱，不言放弃！（二）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月03日 拥抱每一天- 母亲节特辑：只有母爱，不言放弃！（三）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月04日 拥抱每一天- 母亲节特辑：只有母爱，不言放弃！（四）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月05日 拥抱每一天- 母亲节特辑：只有母爱，不言放弃！（五）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月06日 拥抱每一天- 母亲节特辑：只有母爱，不言放弃！（六）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月07日 拥抱每一天- 母亲节特辑：只有母爱，不言放弃！（七）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月08日 拥抱每一天- 母亲节特辑：只有母爱，不言放弃！（八）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月09日 拥抱每一天- 智慧语录：一生做对三件事；拥抱小语：人靠什么活着；寻找生命的真光：父母如何做孩子的情绪教练。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月10日 拥抱每一天- 智慧语录：莫言的一段话；千里思念万里情：只见耶稣，不见一人。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月11日 拥抱每一天- 智慧语录：情谊不在于长短，而在于交心；诗情细语话人生：搭车的女孩。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月12日 拥抱每一天- 智慧语录：处人处心，交人交信；拥抱小语：每个人都应该有第二次机会；说个故事给你听：唯有爱，才能饶恕憎恨的人。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月13日 拥抱每一天- 智慧语录：跟你绝配的爱人，绝不是天造地设的；拥抱小语：世界上最长的路；亮丽人生不是梦：不能与人相处时所产生的问题。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月14日 拥抱每一天- 智慧语录：你是我最重要的决定；拥抱小语：我的信仰；用智慧演绎人生：如果没把孩子管教好，就算成了人生赢家又如何？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月15日 拥抱每一天- 智慧语录：不要放弃自己；拥抱小语：半分钟的犹豫；神的叮咛我最爱：活泼的盼望。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月16日 拥抱每一天- 特辑节目：爬出忧郁的深渊（一）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月17日 拥抱每一天- 特辑节目：爬出忧郁的深渊（二）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月18日 拥抱每一天- 特辑节目：爬出忧郁的深渊（三）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月19日 拥抱每一天- 特辑节目：爬出忧郁的深渊（四）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月20日 拥抱每一天- 智慧语录：俄罗斯的小诗；拥抱小语：铁汉的眼泪；亮丽人生不是梦：防卫的行为", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月21日 拥抱每一天- 智慧语录：我最大的财富就是神；拥抱小语：天父写给我们的一封信；用智慧演绎人生：谈谈孩子该在什么时候说话。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月22日 拥抱每一天- 智慧语录：简单几句话，帮助你处理人际关系；拥抱小语：世上没有绝对的完美；神的叮咛我最爱：活泼的盼望。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月23日 拥抱每一天- 智慧语录：简单的人，不要在复杂的人堆里混；拥抱小语：我唯一能劝你的就是请你善良；寻找生命的真光：太子妃升职记，为何小伙伴们恋恋不舍？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月24日 拥抱每一天- 智慧语录：不去问，不问不伤；拥抱小语：一句话，既能救人，也能害人；千里思念万里情：如何处理人际关系？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月25日 拥抱每一天- 智慧语录：愿你一生，清澈明朗；拥抱小语：他种了三千颗星星；诗情细语话人生：爱的长度。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月26日 拥抱每一天- 说个故事给你听：心尹的故事", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月27日 拥抱每一天- 智慧语录：包容越多，幸福越多；拥抱小语：惩罚正确的人；亮丽人生不是梦：成长需要很长的时间。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月28日 拥抱每一天- 智慧语录：日久见人心，谁会在乎你；拥抱小语：你以为换一个人就好了吗？；用智慧演绎人生：你快乐吗？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月29日 拥抱每一天- 特辑节目：用智慧经营人生（一）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月30日 拥抱每一天- 特辑节目：用智慧经营人生（二）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年05月31日 拥抱每一天- 特辑节目：用智慧经营人生（三）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA1MzEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月01日 拥抱每一天- 特辑节目：用智慧经营人生（四）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MDEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月02日 拥抱每一天- 特辑节目：用智慧经营人生（五）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MDIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月03日 拥抱每一天- 特辑节目：用智慧经营人生（六）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MDMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月04日 拥抱每一天- 特辑节目：用智慧经营人生（七）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MDQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月05日 拥抱每一天- 智慧语录：换个角度，设身处地看别人；拥抱小语：孩子出不出色，与母亲性格影响重大；神的叮咛我最爱：在苦难中的喜乐。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MDUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月06日 拥抱每一天- 智慧语录：送几句话给在路上奋斗的人；拥抱小语：小心陷阱；寻找生命的真光：我多想有个能依靠的爸爸。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MDYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月07日 拥抱每一天- 智慧语录：三点三忘一个有；拥抱小语：人真的有灵魂吗？千里思念万里情：一流女人必备的八个特质。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MDcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月08日 拥抱每一天- 智慧语录：人生太短，明白太晚；诗情细语话人生：求你使我目复盲。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MDgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月09日 拥抱每一天- 智慧语录：教你处理好人际关系；拥抱小语：没有神的日子；说个故事给你听：新年第一天的访客。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MDkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月10日 拥抱每一天- 智慧语录：送给正在感情路上受伤的朋友；亮丽人生不是梦：如何与人相连？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MTAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月11日 拥抱每一天- 智慧语录：在薄情的世界里，深情的活着；用智慧演绎人生：孩子需要的生日礼物，你给他了吗？", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MTEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月12日 拥抱每一天- 智慧语录：好想累的时候，有一个拥抱；拥抱小语：一位妻子的美丽祈祷；神的叮咛我最爱：在苦难中喜乐的秘诀。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MTIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月13日 拥抱每一天- 特辑节目：爱家男人无价宝（一）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MTMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月14日 拥抱每一天- 特辑节目：爱家男人无价宝（二）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MTQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月15日 拥抱每一天- 特辑节目：爱家男人无价宝（三）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MTUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月16日 拥抱每一天- 特辑节目：爱家男人无价宝（四）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MTYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月17日 拥抱每一天- 特辑节目：爱家男人无价宝（五）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MTcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月18日 拥抱每一天- 特辑节目：爱家男人无价宝（六）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MTgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月19日 拥抱每一天- 特辑节目：爱家男人无价宝（七）", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MTkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月20日 拥抱每一天- 智慧语录：干事业，先记住这七个字；拥抱小语：一只麻雀的故事；寻找生命的真光：母亲的四季。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MjAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月21日 拥抱每一天- 智慧语录：有一种情，不求朝暮相处；千里思念万里情：在公司五句不能说的话。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MjEubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月22日 拥抱每一天- 智慧语录：有什么观念就有什么样的人生；拥抱小语：什么叫做执行？；诗情细语话人生：真爱。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MjIubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月23日 拥抱每一天- 说个故事给你听：东方月的见证：奔向净光的高处。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MjMubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月24日 拥抱每一天- 智慧语录：已所不欲，勿施于人；拥抱小语：美丽的伤痕；亮丽人生不是梦：恒久不变的友谊，是神对你的期许。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MjQubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月25日 拥抱每一天- 智慧语录：加油吧，亲爱的自己；拥抱小语：我们该如何向家人传福音？用智慧演绎人生：当孩子哭了，你的第一句话决定着孩子的未来。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MjUubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月26日 拥抱每一天- 智慧语录：日久不一定生情，但一定见人心；拥抱小语：愿舌头上有爱；神的叮咛我最爱：做圣洁的儿女。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MjYubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月27日 拥抱每一天- 智慧语录：人到老年情更真；拥抱小语：婚姻长久的秘诀是做坏人；寻找生命的真光：我追着光芒一路唱。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MjcubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月28日 拥抱每一天- 智慧语录：终身受用的顶级思维；千里思念万里情：比能力更重要的十二种品格。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MjgubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月29日 拥抱每一天- 智慧语录：仅仅如此就好；拥抱小语：面对死亡，你真的是一个无神论者吗？；诗情细语话人生：赞美的力量。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MjkubXAz", counterpart: "", artist: "", image: "true", imgurl: "" },
    { name: "16年06月30日 拥抱每一天- 智慧语录：终身受用的顶级思维；拥抱小语：什么是人真正的教养；说个故事给你听：我不信洋教。", formats: ["mp3"], mp3: "aHR0cDovL21lZGlhLmZlYmNjaGluZXNlLm9yZy9zdHJlYW1pbmcvRUUvZWUxNjA2MzAubXAz", counterpart: "", artist: "", image: "true", imgurl: "" }
];

var songs = JSON.parse(fs.readFileSync('ee2016_' + season + '_songs.json', 'utf8'));
songs.forEach(function(song, indexId) {


    song.title = titles[indexId].name;


});

fs.writeFile("./ee2016_" + season + "_songs_with_title.json", JSON.stringify(songs, null, '\t'));